services:
  - type: web
    name: corelife
    env: node
    buildCommand: npm ci --prefix client --production=false && npm ci --prefix server --production=false && npm run build --prefix client
    startCommand: npm run start --prefix server
    healthCheckPath: /api/health
